// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for macos');
      case TargetPlatform.windows:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for windows');
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDytfxjdwHX8nBa2dqi7aKcor-u05g9fe8',
    appId: '1:370694918896:android:b15f61c36227914b7e6835',
    messagingSenderId: '370694918896',
    projectId: 'reyescompany-dbfd7',
    storageBucket: 'reyescompany-dbfd7.firebasestorage.app',
    databaseURL: 'https://reyescompany-dbfd7-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8uqsaCJpn2w4iwgrKT9xlPPjM1HSlWk',
    appId: '1:370694918896:ios:9adbc18569f01a677e6835',
    messagingSenderId: '370694918896',
    projectId: 'reyescompany-dbfd7',
    storageBucket: 'reyescompany-dbfd7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
    databaseURL: 'https://reyescompany-dbfd7-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ806Y_SWlI9sbCMl4muK2LCM1DK710vU',
    appId: '1:370694918896:web:bd11ab2d968fd68e7e6835',
    messagingSenderId: '370694918896',
    projectId: 'reyescompany-dbfd7',
    authDomain: 'reyescompany-dbfd7.firebaseapp.com',
    storageBucket: 'reyescompany-dbfd7.firebasestorage.app',
    measurementId: 'G-BBN8NQT7PC',
    databaseURL: 'https://reyescompany-dbfd7-default-rtdb.firebaseio.com',
  );
}